### ISSUE TITLE
ValueError: Given mask is invalid because it masks all data

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#172]
Internal Server Error: /images/compare/73/1419
	Traceback (most recent call last):
	  File "/opt/nv_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
	    response = wrapped_callback(request, *callback_args, **callback_kwargs)
	  File "./neurovault/apps/statmaps/views.py", line 734, in compare_images
	    atlas=atlas,custom=custom,corr="pearson")
	  File "/opt/nv_env/src/pybraincompare/compare/compare.py", line 37, in scatterplot_compare
	    masked = do_mask(images=[image1,image2],mask=reference,resample_dim=voxdim,second_mask=pdmask)
	  File "/opt/nv_env/src/pybraincompare/compare/mrutils.py", line 101, in do_mask
	    return apply_mask(images_resamp, reference, dtype='f', smoothing_fwhm=None, ensure_finite=True)
	  File "/opt/nv_env/src/nilearn/nilearn/masking.py", line 564, in apply_mask
	    mask, mask_affine = _load_mask_img(mask_img)
	  File "/opt/nv_env/src/nilearn/nilearn/masking.py", line 51, in _load_mask_img
	    raise ValueError('Given mask is invalid because it masks all data')
	ValueError: Given mask is invalid because it masks all data

**Comment by chrisfilo** [comment]
The error is most likely correct, but it needs to be handled more gracefully (user needs to see a message).

**Comment by vsoch** [comment]
This will be addressed by [this commit](https://github.com/vsoch/pybraincompare/commit/bc54f7cb086fb0fdbe7d60969dd213b06662ac15), and I am still working on tests for it.

**Comment by vsoch** [comment]
[Let there be tests](https://github.com/vsoch/pybraincompare/blob/master/pybraincompare/testing/test_scatterplot_compare.py)!

:space_invader:

**Comment by chrisfilo** [comment]
We need to gracefully take care of this exception on NV side. In other
words user needs to understand what went wrong and why.

**Comment by vsoch** [comment]
Ok, then I'll output custom error messages depending on which one is triggered.

**Comment by vsoch** [comment]
Tests are working locally but failing on Travis, so I'll need to figure that out first.
