### ISSUE TITLE
"ImportError: cannot import name PolymorphicModel" after rebuilding the docker image

### ISSUE THREAD

**Issue by burnash** [NeuroVault/NeuroVault#412]
I'm getting the error after rebuilding the docker image for c2ececda66e0bd62169af2778d6e874d5fe8fe32.

I ran `docker build -t neurovault/neurovault .` and `docker-compose` now fails to start:

~~~
uwsgi_1  | Traceback (most recent call last):
uwsgi_1  |   File "manage.py", line 11, in <module>
uwsgi_1  |     execute_from_command_line(sys.argv)
uwsgi_1  |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
uwsgi_1  |     utility.execute()
uwsgi_1  |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
uwsgi_1  |     django.setup()
uwsgi_1  |   File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
uwsgi_1  |     apps.populate(settings.INSTALLED_APPS)
uwsgi_1  |   File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
uwsgi_1  |     app_config.import_models(all_models)
uwsgi_1  |   File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
uwsgi_1  |     self.models_module = import_module(models_module_name)
uwsgi_1  |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
uwsgi_1  |     __import__(name)
uwsgi_1  |   File "/code/neurovault/apps/statmaps/models.py", line 20, in <module>
uwsgi_1  |     from polymorphic.models import PolymorphicModel
uwsgi_1  | ImportError: cannot import name PolymorphicModel
~~~

I guess the image contains old `django-polymorphic`. Both `requirements.txt` and `Dockerfile` do not specify the version of `django-polymorphic` and `pip` probably uses some cached stuff during the image build.

**Comment by chrisfilo** [comment]
Does setting django polymorphic version in dockerfile to 0.8 (current
release) solve this issue?

**Comment by burnash** [comment]
Let me check. I just confirmed the first part of my guesswork:

~~~
root@nvstaging:/opt/NeuroVault# docker-compose run --rm --service-ports uwsgi bash
Starting neurovault_db_1...
Starting neurovault_redis_1...
root@56ade398ba08:/code# pip freeze | grep django-polymorphic
django-polymorphic==0.7.2
~~~

**Comment by burnash** [comment]
Quick check in the same container yields positive results:

~~~
root@56ade398ba08:/code# python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/code/neurovault/apps/statmaps/models.py", line 20, in <module>
    from polymorphic.models import PolymorphicModel
ImportError: cannot import name PolymorphicModel

root@56ade398ba08:/code# pip install django-polymorphic==0.8.1
Collecting django-polymorphic==0.8.1
  Downloading django_polymorphic-0.8.1-py2.py3-none-any.whl (43kB)
    100% |████████████████████████████████| 45kB 3.8MB/s
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/site-packages (from django-polymorphic==0.8.1)
Installing collected packages: django-polymorphic
  Found existing installation: django-polymorphic 0.7.2
    Uninstalling django-polymorphic-0.7.2:
      Successfully uninstalled django-polymorphic-0.7.2
Successfully installed django-polymorphic-0.8.1

root@56ade398ba08:/code# python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

January 09, 2016 - 01:30:00
Django version 1.7.10, using settings 'neurovault.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
~~~

**Comment by chrisfilo** [comment]
We changed the import to account for changes in django polymorphic 0.8

**Comment by chrisfilo** [comment]
I'll fix the version in another pr

**Comment by burnash** [comment]
Thanks!
