### ISSUE TITLE
Error after pulling dockerfile

### ISSUE THREAD

**Issue by jokedurnez** [NeuroVault/NeuroVault#502]
On a macbook I did the following:

```
docker-machine create --driver virtualbox --virtualbox-memory 1000 neurovault
eval "$(docker-machine env neurovault)"
docker pull neurovault/neurovault
docker-compose up
```

and I get:

```
worker_1 | Traceback (most recent call last):
worker_1 |   File "/usr/local/bin/celery", line 11, in <module>
worker_1 |     sys.exit(main())
worker_1 |   File "/usr/local/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
worker_1 |     main()
worker_1 |   File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
worker_1 |     cmd.execute_from_commandline(argv)
worker_1 |   File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 793, in execute_from_
commandline
worker_1 |     super(CeleryCommand, self).execute_from_commandline(argv)))

worker_1 |   File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_co
mmandline
worker_1 |     return self.handle_argv(self.prog_name, argv[1:])
worker_1 |   File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 785, in handle_argv
worker_1 |     return self.execute(command, argv)
worker_1 |   File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 717, in execute
worker_1 |     ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
worker_1 |   File "/usr/local/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv
worker_1 |     return self(*args, **options)
worker_1 |   File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__
worker_1 |     ret = self.run(*args, **kwargs)
worker_1 |   File "/usr/local/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run
worker_1 |     state_db=self.node_format(state_db, hostname), **kwargs
worker_1 |   File "/usr/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 95, in __init__
worker_1 |     self.app.loader.init_worker()
worker_1 |   File "/usr/local/lib/python2.7/site-packages/celery/loaders/base.py", line 128, in init_worker
worker_1 |     self.import_default_modules()
worker_1 |   File "/usr/local/lib/python2.7/site-packages/celery/loaders/base.py", line 116, in import_defa
ult_modules
worker_1 |     signals.import_modules.send(sender=self.app)
worker_1 |   File "/usr/local/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 166, in se
nd
worker_1 |     response = receiver(signal=self, sender=sender, **named)
worker_1 |   File "/usr/local/lib/python2.7/site-packages/celery/fixups/django.py", line 73, in on_import_m
odules
worker_1 |     self.worker_fixup.validate_models()
worker_1 |   File "/usr/local/lib/python2.7/site-packages/celery/fixups/django.py", line 158, in validate_m
odels
worker_1 |     django_setup()
worker_1 |   File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
worker_1 |     apps.populate(settings.INSTALLED_APPS)
worker_1 |   File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
worker_1 |     app_config = AppConfig.create(entry)
worker_1 |   File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
worker_1 |     module = import_module(entry)
worker_1 |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
worker_1 |     __import__(name)
worker_1 | ImportError: No module named djrill
```

When I build the dockerfile locally, it gives the same errors...

Any ideas?

**Comment by chrisfilo** [comment]
Most likely your source code is out of data (djdrill was remove a while ago). Just do `git pull origin master` (assuming origin points to github.com/NeuroVault/NeuroVault).

**Comment by jokedurnez** [comment]
There's no problems when building the Docker image with the djrill module...

**Comment by jokedurnez** [comment]
yup. sorry :)
