### ISSUE TITLE
Adding bioRxiv DOI to repository does not work

### ISSUE THREAD

**Issue by JoramSoch** [NeuroVault/NeuroVault#738]
When adding a DOI from a corresponding preprint at bioRxiv, interface says "Could not resolve DOI".

**Comment by JoramSoch** [comment]
Example:
- Collection: https://neurovault.org/collections/EKUNXKRB/
- DOI: 10.1101/2020.07.27.220871

**Comment by rwblair** [comment]
Function that extracts metadata from the url expects there to be a journal:
```
>>> get_paper_properties("10.1101/2020.07.27.220871")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/code/neurovault/apps/statmaps/utils.py", line 219, in get_paper_properties
    journal_name = doc.findall(".//journal/journal_metadata/full_title")[0].text
IndexError: list index out of range

```

We could loosen this restriction. Or at the very least provide actual feedback.

**Comment by JoramSoch** [comment]
Hello there! I would be open to this change, i.e. accepting bioRxiv preprints as DOIs. The papers belonging to the collections with which I had this problem are now published, so I can now add DOIs from actual journals to the collections (e.g. NeuroImage and HBM). However, there are two new problems:

- Problem 1: When entering a DOI, NeuroVault renames this collection to the title of the paper. I don't like this (I want to keep the name I gave it) and it also leads to Problem 2.
- Problem 2: When I edit a second collection belonging to the same paper, I get the message "Collection with this DOI of the corresponding paper already exists". Furthermore, because the paper title is scraped to be the collection title, I get the error message "Collection with this Name of collection already exists".

I don't think this will be the only case in which there will be multiple repositories per paper, so please resolve.

**Example:**

- Repository 1: https://neurovault.org/collections/EKUNXKRB/
- Repository 2: https://neurovault.org/collections/QBHNSRVW/
- Paper: http://doi.org/10.1016/j.neuroimage.2021.117820

**Screenshot:**

![Image](https://github.com/user-attachments/assets/d7c9a3ee-b63d-492b-b88e-25cced9ad893)
