### ISSUE TITLE
AFNI detection raises errors

### ISSUE THREAD

**Issue by chrisfilo** [NeuroVault/NeuroVault#74]
Internal Server Error: /images/add_for_neurosynth
	Traceback (most recent call last):
	  File "/opt/nv_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
	    response = wrapped_callback(request, *callback_args, **callback_kwargs)
	  File "/opt/nv_env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
	    return view_func(request, *args, **kwargs)
	  File "./neurovault/apps/statmaps/views.py", line 229, in add_image_for_neurosynth
	    if form.is_valid():
	  File "/opt/nv_env/local/lib/python2.7/site-packages/django/forms/forms.py", line 162, in is_valid
	    return self.is_bound and not bool(self.errors)
	  File "/opt/nv_env/local/lib/python2.7/site-packages/django/forms/forms.py", line 154, in errors
	    self.full_clean()
	  File "/opt/nv_env/local/lib/python2.7/site-packages/django/forms/forms.py", line 354, in full_clean
	    self._clean_form()
	  File "/opt/nv_env/local/lib/python2.7/site-packages/django/forms/forms.py", line 378, in _clean_form
	    cleaned_data = self.clean()
	  File "./neurovault/apps/statmaps/forms.py", line 404, in clean
	    if nii_tmp is not None and detect_afni4D(nii_tmp):
	  File "./neurovault/apps/statmaps/utils.py", line 220, in detect_afni4D
	    return bool(len(get_afni_subbrick_labels(nii_file)) > 1)
	  File "./neurovault/apps/statmaps/utils.py", line 235, in get_afni_subbrick_labels
	    tree = etree.fromstring(header[0].get_content())
	  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src/lxml/lxml.etree.c:68106)
	  File "parser.pxi", line 1785, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:102455)
	  File "parser.pxi", line 1673, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:101284)
	  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:96466)
	  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91275)
	  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92461)
	  File "parser.pxi", line 622, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91757)
	XMLSyntaxError: Extra content at the end of the document, line 6, column 1
	
	Request repr():
	<WSGIRequest
	path:/images/add_for_neurosynth,
	GET:<QueryDict: {}>,
	POST:<QueryDict: {u'name': [u'multiple sclerosis '], u'tags': [u''], u'submit': [u'Submit'], u'map_type': [u'Z'], u'csrfmiddlewaretoken': [u'CPwZHQ1mkvNuKac6Kgl8WpoPEQ3tsXu8'], u'hdr_file': [u''], u'description': [u'VBM gray matter decrease']}>,
	COOKIES:{'__atuvc': '3%7C51',
	 '__atuvs': '54933e96a27c4623001',
	 '__utma': '90927109.1402959033.1418932513.1418932513.1418935955.2',
	 '__utmb': '90927109.8.10.1418935955',
	 '__utmc': '90927109',
	 '__utmli': 'submit-id-submit',
	 '__utmz': '90927109.1418932513.1.1.utmcsr=neurosynth.org|utmccn=(referral)|utmcmd=referral|utmcct=/decode/',
	 '__uvt': '',
	 'csrftoken': 'CPwZHQ1mkvNuKac6Kgl8WpoPEQ3tsXu8',
	 'sessionid': '5he7nrlmap4fyngv43y5jvl4idsnerld',
	 'uvts': '9R1nMRBssD7e3PE'},
	META:{'CONTENT_LENGTH': '2342551',
	 'CONTENT_TYPE': 'multipart/form-data; boundary=----WebKitFormBoundaryRULlozBEXpBeuV4i',
	 u'CSRF_COOKIE': u'CPwZHQ1mkvNuKac6Kgl8WpoPEQ3tsXu8',
	 'DOCUMENT_ROOT': '/var/www',
	 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
	 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
	 'HTTP_ACCEPT_LANGUAGE': 'it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4',
	 'HTTP_CACHE_CONTROL': 'max-age=0',
	 'HTTP_CONNECTION': 'keep-alive',
	 'HTTP_CONTENT_LENGTH': '2342551',
	 'HTTP_CONTENT_TYPE': 'multipart/form-data; boundary=----WebKitFormBoundaryRULlozBEXpBeuV4i',
	 'HTTP_COOKIE': '__uvt=; sessionid=5he7nrlmap4fyngv43y5jvl4idsnerld; __atuvc=3%7C51; __atuvs=54933e96a27c4623001; csrftoken=CPwZHQ1mkvNuKac6Kgl8WpoPEQ3tsXu8; __utma=90927109.1402959033.1418932513.1418932513.1418935955.2; __utmb=90927109.8.10.1418935955; __utmc=90927109; __utmz=90927109.1418932513.1.1.utmcsr=neurosynth.org|utmccn=(referral)|utmcmd=referral|utmcct=/decode/; uvts=9R1nMRBssD7e3PE; __utmli=submit-id-submit',
	 'HTTP_HOST': 'neurovault.org',
	 'HTTP_ORIGIN': 'http://neurovault.org',
	 'HTTP_REFERER': 'http://neurovault.org/images/add_for_neurosynth',
	 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36',
	 'PATH_INFO': u'/images/add_for_neurosynth',
	 'QUERY_STRING': '',
	 'REMOTE_ADDR': '2.36.196.177',
	 'REMOTE_PORT': '50656',
	 'REQUEST_METHOD': 'POST',
	 'REQUEST_URI': '/images/add_for_neurosynth',
	 u'SCRIPT_NAME': u'',
	 'SERVER_NAME': 'neurovault.org',
	 'SERVER_PORT': '80',
	 'SERVER_PROTOCOL': 'HTTP/1.1',
	 'UWSGI_APPID': 'neurovault.org|',
	 'uwsgi.core': 1,
	 'uwsgi.node': 'neurovault.org',
	 'uwsgi.version': '2.0.8',
	 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7f5288453420>,
	 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
	 'wsgi.input': <uwsgi._Input object at 0x7f525ef48708>,
	 'wsgi.multiprocess': True,
	 'wsgi.multithread': True,
	 'wsgi.run_once': False,
	 'wsgi.url_scheme': 'http',
	 'wsgi.version': (1, 0)}>

**Comment by infocortex** [comment]
One of these should be fixed in 0a72309a0676bd82c1818f8adc5ad9fda9c93f2d, but I lack an SPM2 Analyze nifti to reproduce.

The `add_for_neurosynth` one also possibly addressed by 4b5dde24f9c30d2b523cc91b866f75192b4d9026, but that one is probably related to bad url of unknown origin: `'/collections/<>/upload_folder',` :grey_question:
