### ISSUE TITLE
The repo doesn't build anymore

### ISSUE THREAD

**Issue by abitrolly** [NeuroVault/NeuroVault#743]
Even after https://github.com/NeuroVault/NeuroVault/pull/742 the attempt to build the Dockerfile fails, because of outdated fork of `django-guardian` that doesn't pin to specific version of `pytest-runner`, compatible with Python 2.7. The solution is to update code in https://github.com/django-guardian/django-guardian/pull/421#issuecomment-225353878 to linked PR, but I can't do this.

Just found this repo unmerged on my disk.
```
...
Collecting django-guardian
  Cloning https://github.com/benkonrath/django-guardian.git (to revision 7cded9081249e9a4cd9f5cd85e67cf843c138b0c) to /tmp/pip-install-I4rLnT/django-guardian
  Running command git clone -q https://github.com/benkonrath/django-guardian.git /tmp/pip-install-I4rLnT/django-guardian
  Running command git rev-parse -q --verify 'sha^7cded9081249e9a4cd9f5cd85e67cf843c138b0c'
  Running command git fetch -q https://github.com/benkonrath/django-guardian.git 7cded9081249e9a4cd9f5cd85e67cf843c138b0c
  Running command git checkout -q 7cded9081249e9a4cd9f5cd85e67cf843c138b0c
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-I4rLnT/django-guardian/setup.py'"'"'; __file__='"'"'/tmp/pip-install-I4rLnT/django-guardian/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ERtOTO
         cwd: /tmp/pip-install-I4rLnT/django-guardian/
    Complete output (106 lines):
    /tmp/easy_install-ym540F/pytest-runner-5.3.0/temp/easy_install-Cbg1Lv/setuptools_scm-6.0.1/src
    <pkg_resources.WorkingSet object at 0x7fb2d710abd0>
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-I4rLnT/django-guardian/setup.py", line 57, in <module>
        cmdclass={'flakes': RunFlakesCommand},
      File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
...
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-ym540F/pytest-runner-5.3.0/temp/easy_install-Cbg1Lv/setuptools_scm-6.0.1/setup.py", line 52, in <module>
        'Programming Language :: Python :: 3.3',
      File "/tmp/easy_install-ym540F/pytest-runner-5.3.0/temp/easy_install-Cbg1Lv/setuptools_scm-6.0.1/setup.py", line 29, in scm_config
        zip_safe=False,
      File "/tmp/easy_install-ym540F/pytest-runner-5.3.0/temp/easy_install-Cbg1Lv/setuptools_scm-6.0.1/src/setuptools_scm/__init__.py", line 8, in <module>
      File "/tmp/easy_install-ym540F/pytest-runner-5.3.0/temp/easy_install-Cbg1Lv/setuptools_scm-6.0.1/src/setuptools_scm/config.py", line 6, in <module>
      File "/tmp/easy_install-ym540F/pytest-runner-5.3.0/temp/easy_install-Cbg1Lv/setuptools_scm-6.0.1/src/setuptools_scm/utils.py", line 41
        print(*k)
              ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error: error building at STEP "RUN pip install cython                 scipy                 scikit-learn==0.17.1                 pandas==0.20.3                 h5py==2.6.0                 matplotlib==1.5.1                 scikit-image==0.12.3                 redis==2.10.6                 celery[redis]==3.1.24                 certifi==2015.04.28                 cognitiveatlas                 'Django==1.8.8'                 djangorestframework==3.4.7                 django-celery                 django-chosen                 django-cleanup==0.4.2                 git+git://github.com/mariagardbraga/django-crispy-forms.git@78a34a0db9715ed57fc912805751a987c82e25e5#egg=django-crispy-forms                 django-datatables-view                 'django-dbbackup<2.3'                 django-dirtyfields                 django-file-resubmit==0.4.3                 django-filter==1.1.0                 django-fixture-media                 django-form-utils                 'django-hstore==1.4.1'                 'django-oauth-toolkit==0.10.0'                 django-polymorphic==0.9.2                 django-sendfile                 django-taggit==0.22.2                 django-taggit-templatetags                 django-mailgun-provider                 'dropbox==1.6'                 lxml                 networkx                 nibabel==2.1.0                 nidmresults==0.3.2                 nidmfsl==0.3.4                 nilearn==0.4.2                 numexpr                 raven==6.9.0                 Pillow==4.1.1                 psycopg2==2.7.3.2                 pybraincompare==0.1.18                 python-openid                 'python-social-auth==0.2.13'                 'rdflib>=4.1.0'                 requests                 requests-oauthlib                 shapely                 uwsgi                 zipstream                 html5lib                 https://github.com/gallantlab/pycortex/archive/fe58400c8c3a3187d930b8a696cda8fec62c0f19.zip                 pytest-runner==5.2                 setuptools_scm==5.0.2                 git+https://github.com/benkonrath/django-guardian.git@7cded9081249e9a4cd9f5cd85e67cf843c138b0c#egg=django-guardian                 nidmviewer==0.1.3                 git+git://github.com/neurostuff/NiMARE.git@608516ec3034e356326dfe70df5e9ed77efd2be8                 tables                 statsmodels": error while running runtime: exit status 1

```

**Comment by rwblair** [comment]
#756 should resolve this.
