### ISSUE TITLE
Problems with setting map type in upload folder

### ISSUE THREAD

**Issue by chrisgorgo** [NeuroVault/NeuroVault#78]
Related to polymorphic refactor:

```
Internal Server Error: /collections/276/upload_folder
Traceback (most recent call last):
  File "/opt/nv_env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/nv_env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./neurovault/apps/statmaps/views.py", line 327, in upload_folder
    map_type = Image.T
  File "/opt/nv_env/local/lib/python2.7/site-packages/polymorphic/base.py", line 246, in __getattribute__
    return super(PolymorphicModelBase, self).__getattribute__(name)
AttributeError: type object 'Image' has no attribute 'T'

Request repr():
<WSGIRequest
path:/collections/276/upload_folder,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'paths': [u''], u'csrfmiddlewaretoken': [u'qCdlxOlSetZ2Ko1ebtVKY1vqhz286RFz'], u'file_input[]': [u'']}>,
COOKIES:{'__atuvc': '1%7C50%2C4%7C51',
 '__utma': '90927109.612673957.1418245354.1418933642.1418939749.4',
 '__utmb': '90927109.38.10.1418939749',
 '__utmc': '90927109',
 '__utmli': 'upload_archive',
 '__utmz': '90927109.1418939749.4.3.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)',
 '__uvt': '',
 'csrftoken': 'qCdlxOlSetZ2Ko1ebtVKY1vqhz286RFz',
 'sessionid': '6gh5vicyysq0kr511ng0v60b8c835ghj',
 'uvts': '2Qsk6YrZS7fPbJYw'},
META:{'CONTENT_LENGTH': '782931',
 'CONTENT_TYPE': 'multipart/form-data; boundary=---------------------------1320791347551278679440225896',
 u'CSRF_COOKIE': u'qCdlxOlSetZ2Ko1ebtVKY1vqhz286RFz',
 'DOCUMENT_ROOT': '/var/www',
 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_CONTENT_LENGTH': '782931',
 'HTTP_CONTENT_TYPE': 'multipart/form-data; boundary=---------------------------1320791347551278679440225896',
 'HTTP_COOKIE': '__utma=90927109.612673957.1418245354.1418933642.1418939749.4; __utmz=90927109.1418939749.4.3.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); __uvt=; uvts=2Qsk6YrZS7fPbJYw; csrftoken=qCdlxOlSetZ2Ko1ebtVKY1vqhz286RFz; __atuvc=1%7C50%2C4%7C51; __utmc=90927109; sessionid=6gh5vicyysq0kr511ng0v60b8c835ghj; __utmb=90927109.38.10.1418939749; __utmli=upload_archive',
 'HTTP_HOST': 'neurovault.org',
 'HTTP_REFERER': 'http://neurovault.org/collections/276/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0',
 'PATH_INFO': u'/collections/276/upload_folder',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '83.76.198.4',
 'REMOTE_PORT': '48301',
 'REQUEST_METHOD': 'POST',
 'REQUEST_URI': '/collections/276/upload_folder',
 u'SCRIPT_NAME': u'',
 'SERVER_NAME': 'neurovault.org',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'UWSGI_APPID': 'neurovault.org|',
 'uwsgi.core': 0,
 'uwsgi.node': 'neurovault.org',
 'uwsgi.version': '2.0.8',
 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7f84e0a37420>,
 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
 'wsgi.input': <uwsgi._Input object at 0x7f84c661bd20>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>
```

**Comment by infocortex** [comment]
fixed in 310fb576b98aeb15bd324100a72835f67798aed1 (#94)
