### ISSUE TITLE
NeuroVault seems to be down

### ISSUE THREAD

**Issue by ymzayek** [NeuroVault/NeuroVault#804]
We started having a CI failure yesterday concerning issues retrieving neurovault data with nilearn. A call like `python -c "from nilearn import datasets; datasets.fetch_neurovault_motor_task()" ` results in: 
```bash
Could not get batch from https://neurovault.org/api/images/10426
Traceback (most recent call last):
  File "/home/yasmin/nilearn/nilearn/nilearn/datasets/neurovault.py", line 996, in _get_batch
    resp.raise_for_status()
  File "/home/yasmin/miniconda3/envs/nilearn-dev/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://neurovault.org/api/images/10426
```

Now I get the same error when trying to access https://www.neurovault.org/. Probably someone is already aware but just wanted to leave this here for reference. Thanks!

**Comment by ymzayek** [comment]
It looks like this has been resolved. Closing
